apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: appconfigs.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                appName:
                  type: string
                replicas:
                  type: integer
                  minimum: 1
                  maximum: 100
                  default: 1
                image:
                  type: string
                  description: "The Docker image for the application."
                configMapRef:
                  type: string
                  description: "Reference to the ConfigMap holding configuration."
                environment:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      value:
                        type: string
              required:
                - appName
                - image
            status:
              type: object
              properties:
                availableReplicas:
                  type: integer
                updatedReplicas:
                  type: integer
  scope: Namespaced
  names:
    plural: appconfigs
    singular: appconfig
    kind: AppConfig
    shortNames:
      - acfg
