name: Notify dump repo on Tag Push

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  notify_repo_b:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout leased-based-le repository
        uses: actions/checkout@v4

      - name: Get tag from event
        id: extract_tag
        run: |
          TAG=${{ github.ref }}
          TAG=${TAG#refs/tags/}
          echo "TAG=${TAG}" >> $GITHUB_ENV
          echo "Extracted tag: ${TAG}"

      - name: Copy CRDs to a temporary directory
        run: |
          mkdir -p /tmp/crds
          cp -r $GITHUB_WORKSPACE/crd/* /tmp/crds/

      - name: Upload CRDs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: crds
          path: /tmp/crds

      - name: Checkout dump-crds repository 
        uses: actions/checkout@v4
        with: 
          repository: olamilekan000/dump-crds
          token: ${{ secrets.PAT }}

      - name: Create and checkout new branch
        run: |
          git checkout -b release-${{ env.TAG }}          

      - name: Create a directory for the tag
        run: |
          mkdir -p releases/download/${{ env.TAG }}  

      - name: Download CRDs artifact directly into the tag directory
        uses: actions/download-artifact@v4
        with:
          name: crds
          path: releases/download/${{ env.TAG }}

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "add CRDs for version ${{ env.TAG }}"
          git push origin release-${{ env.TAG }}
